cecho("Centered, mirror caps, spacer inside")
cecho(calign("some text", {alignment = "center", width = 30, cap = "{[[", spacer = "=", inside = true, mirror = true}))
cecho("\nCentered, mirror caps, spacer outside")
cecho(calign("some text", {alignment = "center", width = 30, cap ="{[[", spacer = "=", inside = false, mirror = true}))
cecho("\nCentered, no mirroring, spacer inside")
cecho(calign("some text", {alignment = "center", width = 30, cap = "[Bal]", spacer = "=", inside = true, mirror = false}))
cecho("\nCentered, no mirroring, spacer outside")
cecho(calign("some text", {alignment = "center", width = 30, cap = "[Bal]", spacer = "=", inside = false, mirror = false}))
cecho("\nLeft aligned, spacer inside")
cecho(calign("some text", {alignment = "left", width = 30, cap = "|", spacer = ".", inside = true}))
cecho("\nLeft aligned, spacer outside")
cecho(calign("some text", {alignment = "left", width = 30, cap = "|", spacer = "=", inside = false}))
cecho("\nRight aligned, spacer inside")
cecho(calign("some text", {alignment = "right", width = 30, cap = "|", spacer = ".", inside = true}))
cecho("\nRight aligned, spacer outside")
cecho(calign("some text", {alignment = "right", width = 30, cap = "|", spacer = "=", inside = false}))
cecho("\n\nNow with colors!!")
cecho("\nCentered, mirror caps, spacer inside, <green>capColor <white>, <purple>spacerColor <white>, <red>textColor<white>")
cecho(calign("some text", {alignment = "center", width = 30, cap = "{[[", spacer = "=", inside = true, mirror = true, capColor = "<green>", spacerColor = "<purple>", textColor = "<red>"}))
cecho("\nCentered, mirror caps, spacer outside, <green>capColor <white>, <purple>spacerColor <white>, <red>textColor<white>")
cecho(calign("some text", {alignment = "center", width = 30, cap = "{[[", spacer = "=", inside = false, mirror = true, capColor = "<green>", spacerColor = "<purple>", textColor = "<red>"}))
cecho("\nCentered, no mirroring, spacer inside, <green>capColor <white>, <purple>spacerColor <white>, <red>textColor<white>")
cecho(calign("some text", {alignment = "center", width = 30, cap = "[Bal]", spacer = "=", inside = true, mirror = false, capColor = "<green>", spacerColor = "<purple>", textColor = "<red>"}))
cecho("\nCentered, no mirroring, spacer outside, <green>capColor <white>, <purple>spacerColor <white>, <red>textColor<white>")
cecho(calign("some text", {alignment = "center", width = 30, cap = "[Bal]", spacer = "=", inside = false, mirror = false, capColor = "<green>", spacerColor = "<purple>", textColor = "<red>"}))
cecho("\nLeft Aligned, spacer inside, <green>capColor <white>, <purple>spacerColor <white>, <red>textColor<white>")
cecho(calign("some text", {alignment = "left", width = 30, cap = "|", spacer = ".", inside = true, capColor = "<green>", spacerColor = "<purple>", textColor = "<red>"}))
cecho("\nLeft Aligned, spacer outside, <green>capColor <white>, <purple>spacerColor <white>, <red>textColor<white>")
cecho(calign("some text", {alignment = "left", width = 30, cap = "|", spacer = "=", inside = false, capColor = "<green>", spacerColor = "<purple>", textColor = "<red>"}))
cecho("\nRight Aligned, spacer inside, <green>capColor <white>, <purple>spacerColor <white>, <red>textColor<white>")
cecho(calign("some text", {alignment = "right", width = 30, cap = "|", spacer = ".", inside = true, capColor = "<green>", spacerColor = "<purple>", textColor = "<red>"}))
cecho("\nRight Aligned, spacer outside, <green>capColor <white>, <purple>spacerColor <white>, <red>textColor<white>")
cecho(calign("some text", {alignment = "right", width = 30, cap = "|", spacer = "=", inside = false, capColor = "<green>", spacerColor = "<purple>", textColor = "<red>"}))
 

